### ISSUE TITLE
Version in package.json does not match latest tag

### ISSUE THREAD

**Issue by badazz91** [lightblade/ember-cli-d3#74]
Should be ` "version": "1.1.7"`, but is ` "version": "1.1.6"` instead. Causes issues when installing it via `npm`.

**Comment by ming-codes** [comment]
You mean you are installing from GitHub?

**Comment by robd91** [comment]
I have an custom ember-addon that depends on `ember-cli-d3` in version `1.1.7`. This addons adds the `ember-cli-d3` package via its blueprint to ember-projects that use this custom addon.

Simply put: The blueprint adds following line to the package.json of the consuming ember app:

`"ember-cli-d3": "1.1.7"`

So I would think that installation is done just normally via `npm`.

But then the installation fails because there is no `1.1.7` available apparently.

**Comment by ming-codes** [comment]
Ah yes, I found what's wrong. The change is in my local that was never pushed. It's fixed now.
